### ISSUE TITLE
Problem with more than one device on the bus

### ISSUE THREAD

**Issue by StefanR71** [rellit/resol-vbus-python#11]
Hi,

nice script and it works very well with the Vitosolic on the bus, now i connected to the LAN adapter a second device and i got very often a error. I can try the command several times and then i got the expected output.

Most times i got this error message:

Traceback (most recent call last):
  File "resol.py", line 250, in <module>
    load_data()
  File "resol.py", line 65, in load_data
    print(format_message_pv1(msg))
  File "resol.py", line 170, in format_message_pv1
    integrated = integrate_septett(msg[9+(i*6):15+(i*6)])
  File "resol.py", line 218, in integrate_septett
    septet = ord(frame[4])
IndexError: string index out of range

And some times:

Traceback (most recent call last):
  File "resol.py", line 250, in <module>
    load_data()
  File "resol.py", line 65, in load_data
    print(format_message_pv1(msg))
  File "resol.py", line 176, in format_message_pv1
    parsed += ("    CHECKSUM"+str(i+1)).ljust(15,'.')+": " + format_byte(msg[14+(i*6)]) + "\n"
IndexError: string index out of range

I have a Vitosolic 200 and a DelteTherm HC Max connected to the vbus. I put both devices in a single spec file. And configured only some specific values in the spec file to output.

When i switch off the DeltaTherm, the Vitosolic is woring fine again. 

Perhaps you have a hint to help, becasue i'm not a python specialist.

Thank you very much!

**Comment by rellit** [comment]
Hi,

I'm verry sorry. Never tested a multi device Setup.
Unfortunately I also have no longer access to my old setup, so I cannot give any support to the scripts.

Bye
Tim

Am 3. August 2022 17:13:51 MESZ schrieb StefanR71 ***@***.***>:

**Comment by StefanR71** [comment]
Hi Tim,

i got now a 2nd LAN adapter, so i have one IP for each device. That is working more stable...
