### ISSUE TITLE
Troubles for Resol Delta Sol E V2

### ISSUE THREAD

**Issue by fasutec** [rellit/resol-vbus-python#9]
I've got the Resol Delta Sol E V2 controller connected through Vbus/Lan adapter to my network.

I generated the Json Spec like described and adapted the config file.

But when I start the script it comes to following Error:

pi@raspberrypi:~/Documents/resol-vbus-python $ $json = `python resol.py`
Traceback (most recent call last):
  File "resol.py", line 250, in <module>
    load_data()
  File "resol.py", line 66, in load_data
    parse_payload(msg)
  File "resol.py", line 158, in parse_payload
    result[get_source_name(msg)][field['name'][0]] = str(gb(payload, int(field['offset']), int(field['offset'])+((int(field['bitSize'])+1) / 8)) * (float(field['factor']) if field.has_key('factor') else 1)) + (field['unit'] if 'unit' in field else '')
KeyError: 'offset'
bash: =: Kommando nicht gefunden.

Has anybody an idea what the problem could be? I would be very gratefully...

In the zip-file I've got the config file and the generated Json file.
[DeltaSolE.zip](https://github.com/rellit/resol-vbus-python/files/7257433/DeltaSolE.zip)

**Comment by hmueller01** [comment]
Testing in my setup I got this errror:
```
Traceback (most recent call last):
  File "./resol.py", line 250, in <module>
    load_data()
  File "./resol.py", line 66, in load_data
    parse_payload(msg)
  File "./resol.py", line 155, in parse_payload
    if packet['source'].lower() == get_source(msg).lower() and packet['destination'].lower() == get_destination(msg).lower() and packet['command'].lower() == get_command(msg).lower():
KeyError: 'source'
```

I removed `#item` entries
```
@@ -311,11 +311,6 @@
         ]
       },
       {
-        "#item": {
-          "#comment1": " DeltaSol E V2 [WMZ] "
-        }
-      },
-      {
         "destination": "0x0010",
         "source": "0x1051",
         "command": "0x0100",
@@ -365,11 +360,6 @@
         ]
       },
       {
-        "#item": {
-          "#comment2": " DeltaSol E V2 - Estrichtrocknungsprotokoll [Heizkreis #] "
-        }
-      },
-      {
         "destination": "0x0010",
         "source": "0x1040",
         "sourceMask": "0xFFF0",

```
This removes the error. Hope this helps you.

Holger
